#!/usr/bin/bash
# fif: find in files
# usage: fif <dir in single quotes> <search string>
# todo: remove the single quotes from dir

# if dir omitted, use current dir
if [ $# == 1 ]
then
    #  echo "one argument: $1"
    search=$1
    grep -Rn . -e $search
else
    dir=$1
    search=$2
    grep -Rn $dir -e $search
fi

# grep options:
# -R: recursive in each dir
# -n: line number
