#!/usr/bin/bash
# fif: find in files
# usage: fif <search string> [dir]

# if dir omitted, use current dir
if [ $# == 1 ]
then
    #  echo "one argument: $1"
    search=$1
    grep -Rn . -e $search
else
    search=$1
    dir=$2
    grep -Rn $dir -e $search
fi

# grep options:
# -R: recursive in each dir
# -n: line number
