#!/usr/bin/bash

a_flag=""
while getopts 'a:' flag; do
    case "$flag" in
        a) a_flag=${OPTARG} ;;
    esac
done
shift $(($OPTIND - 1))

owner=$1
repo=$2
if [[ $a_flag == "" ]]; then
  gh api "repos/$owner/$repo/collaborators" | jq '.[] | .login' -r
else
  echo -n "adding user: "
  gh api -XPUT "repos/$owner/$repo/collaborators/$a_flag" -f permission=push | jq ".invitee.login" -r
fi
